Hw1 Clean code: Add Github Actions for linters, refactor the project
GenesisEducationKyiv/main-project-CalculusEnjoyer pull request #2
Opened 2023-06-18 15:56 UTC by CalculusEnjoyer

2023-06-20 19:59 UTC, Miha-s requested changes
It was pretty cool idea to add linter to github ci, I will borrow that if you don't mind 🙃

2023-06-20 19:59 UTC, Miha-s commented on services/storage/emails/storage_service_impl.go
> +	allData, err := r.Orchestrator.GetAllRecords()
Maybe it would be better no name variable somethind like
`allEmails, usersEmails, etc`

2023-06-20 19:59 UTC, Miha-s commented on services/storage/emails/storage_service_impl.go
> +			return true, err
If you are sure that err won't be other than nil, I suppose it would be more conscious to return just nil

2023-06-20 19:59 UTC, Miha-s commented on services/storage/emails/orchestrator/file_orchestratror.go
> +func (o *FileOrchestrator) GetAllRecords() (records [][]string, err error) {
I suppose it would be better to return one dimensional array, if you do not have any additional information related to email

2023-06-20 19:59 UTC, Miha-s commented on services/storage/emails/orchestrator/file_orchestratror.go
> +	err := godotenv.Load()
IMHO it would be better to create some instance that will manage all configuration.
Because when you will want to change source of configs you will be needed to change all occurrences of `godotenv`

2023-06-20 19:59 UTC, Miha-s commented on services/api/grpc/client/currency/currency_client.go
> +func (c *CurrencyGRPCClient) GetRate(request *proto.RateRequest) (*proto.RateResponse, error) {
I suppose it would be better to accept parameters and create proto.RateRequest inside function, thus that will decrease coupling between proto library and other components.
The same with other proto clients

2023-06-20 19:59 UTC, Miha-s commented on services/currency/rate/rate_service_impl.go
> +	return messages.RateResult{Rate: btcRate, Timestamp: time.Now().String()}, err
You can emulate `time.Now().String()` by some factory method, but I suppose you know that too, after today's lecture 🤠

2023-06-21 23:27 UTC, CalculusEnjoyer commented on services/storage/emails/storage_service_impl.go
> +	allData, err := r.Orchestrator.GetAllRecords()
Reasonable,  will fix

2023-06-21 23:28 UTC, CalculusEnjoyer commented on services/storage/emails/orchestrator/file_orchestratror.go
> +func (o *FileOrchestrator) GetAllRecords() (records [][]string, err error) {
Yeah, should hide this logic in FileOrchestrator

2023-06-21 23:28 UTC, CalculusEnjoyer commented on services/storage/emails/orchestrator/file_orchestratror.go
> +	err := godotenv.Load()
Yeah, definitely, this will help with e2e tests as well

2023-06-21 23:30 UTC, CalculusEnjoyer commented on services/currency/rate/rate_service_impl.go
> +	return messages.RateResult{Rate: btcRate, Timestamp: time.Now().String()}, err
haha, agree  😄

2023-06-23 08:18 UTC, andrey-filenko-quarks-tech commented on services/api/grpc/client/currency/currency_client.go
> +	conn := c.getConnection()
getConnection is kind of heavy operation, I guess it should be created once on client initialization

2023-06-23 08:18 UTC, andrey-filenko-quarks-tech commented on services/api/grpc/client/currency/currency_client.go
> +	response, err := client.GetRate(context.Background(), modelRateToProto(request))
context should be passed as method argument

2023-06-23 11:51 UTC, andrey-filenko-quarks-tech commented on services/api/rest/ctrl/email_controller.go
> +		err = e.emailExecutor.SendEmail(models.SendEmailsRequest{
error is rewritten every time here, if the first one response has failed, and last one succeded - error would not be handled

2023-06-23 11:54 UTC, andrey-filenko-quarks-tech commented on services/storage/emails/storage_service_impl.go
> +	if !isExist && err == nil {
err is 100% here is nil

2023-06-23 11:57 UTC, andrey-filenko-quarks-tech commented on services/storage/emails/storage_service_impl.go
conssider naming smth like inmemory.go

2023-06-25 08:01 UTC, CalculusEnjoyer commented on services/storage/emails/storage_service_impl.go
Yeah, would be more laconic

2023-06-25 08:02 UTC, CalculusEnjoyer commented on services/storage/emails/storage_service_impl.go
> +	if !isExist && err == nil {
Oops, yeah  😅, changed

2023-06-25 08:02 UTC, CalculusEnjoyer commented on services/api/rest/ctrl/email_controller.go
> +		err = e.emailExecutor.SendEmail(models.SendEmailsRequest{
Agree, refactored it

2023-06-25 08:02 UTC, CalculusEnjoyer commented on services/api/grpc/client/currency/currency_client.go
> +	response, err := client.GetRate(context.Background(), modelRateToProto(request))
Changed👍

2023-06-25 08:05 UTC, CalculusEnjoyer commented on services/api/grpc/client/currency/currency_client.go
> +	conn := c.getConnection()
Agree, now the connection is being stored in a struct, and also introduced the `connection()` method, that checks if the stored connection is still in the Ready state and if not - tries to reconnect.

2023-06-25 21:30 UTC, Miha-s approved these changes
Good job, bro! 😎

2023-06-29 19:20 UTC, merged